Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [9]:
import numpy as np
def geo_progession(ip_vector,n,increasing=False):
    if increasing == False:
        op_mat = np.array([i**(n-j-1)for i in ip_vector for j in range(n)]).reshape(ip_vector.size,n)
    else:
        op_mat = np.array([i**j for i in ip_vector for j in range(n)]).reshape(ip_vector.size,n)
    return op_mat
a=np.array([1,2,3,4,5])
print(geo_progession(a,3,True))
print(geo_progession(a,4,False))

[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]
[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]


Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.
The moving average sequence has n-k+1 elements

In [6]:
def mov_avg(a,n):
    x=np.cumsum(a,dtype=float)
    x[n:] = x[n:]- x[:-n]
    return x[n-1:]/n
a=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
print(mov_avg(a,3))

[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
